# -*- coding: utf-8 -*-
"""crop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hnvRrHplGW819hwA7Ue2OC7fvfkeNOxF
"""

from google.colab import drive
drive.mount('/content/drive')

ext = 'drive/MyDrive/CV_Images/'

import cv2
import numpy as np
import json
import os

def cropped(ele_name,tr_or_te):
    input_path = ele_name + tr_or_te
    cropped_path = ele_name + 'cropped_' + tr_or_te
    #print(cropped_path)
    #cropped_path = 'drive/MyDrive/CV_Images/1015/cropped_train/'
    for image in os.listdir(cropped_path):
      try:
        os.remove(f'{cropped_path}{image}')
      except:
        "Meh"
    for each in os.listdir(input_path):
        ext = os.path.splitext(each)[-1]
        if ext == '.json':
            filename = os.path.splitext(each)[0]
            f = open(input_path+filename+'.json')#'1019/train/IMG_6177.json')
            data = json.load(f)
            [[r1,c1],[r2,c2]] = data['shapes'][0]['points']
            img = cv2.imread(input_path+filename+'.JPG')
            cropped = img[np.int64(np.floor(c1)):np.int64(np.floor(c2)),np.int64(np.floor(r1)):np.int64(np.floor(r2))]
            cv2.imwrite(cropped_path + filename +'.jpg', cropped)

for elephant in os.listdir(ext):
  ele_name = ext + elephant +'/'
  for i in ['train/','test/']:
    tr_or_te = i
    cropped(ele_name,tr_or_te)

# for elephant in ['1015','1019']:  # Shashank's folders
#   ele_name = ext + elephant +'/'
#   for i in ['train/','test/']:
#     tr_or_te = i
#     cropped(ele_name,tr_or_te)









